default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

local: &local
  <<: *default
  host: postgres
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *local
  database: development

test:
  <<: *local
  database: test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
